version: '3.8'

services:
  comiclib-api:
    build: ./comiclib-api
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    env_file:
      - ./comiclib-api/.env

  comiclib-app:
    build: ./comiclib-app
    ports:
      - "8080:80"
    depends_on:
      - comiclib-api
